version: "3.8"
services:
  flask_deplay_api:
    image: suvambasak/pyimg:delayapi
    ports:
      - 80:5000

  rpi_ledblink:
    image: suvambasak/pyimg:ledblink
    privileged: true
    depends_on:
      - flask_deplay_api
    volumes:
      - /sys:/sys
      - /usr:/usr
    environment:
      - IP=192.168.0.112
